Add tentusscher test. It fails in the generated I method with:
Traceback (most recent call last):
  File "tentusscher_test.py", line 73, in <module>
    for (timestep, vs, u) in solutions:
  File "/home/hake/local/lib/python2.7/site-packages/beatadjoint/splittingsolver.py", line 103, in solve
    (vs, u) = self.step(timestep, self.vs_)
  File "/home/hake/local/lib/python2.7/site-packages/beatadjoint/splittingsolver.py", line 129, in step
    vs_star = self.ode_step((t0, t), ics)
  File "/home/hake/local/lib/python2.7/site-packages/beatadjoint/splittingsolver.py", line 182, in ode_step
    I_theta = - (theta*I_ion(v, s) + (1 - theta)*I_ion(v_, s_))
  File "/home/hake/hg/projects/adjoint-beat/test/no-adjoints/tentusscher/tentusscher_2004_mcell.py", line 71, in I
    states = split(s)
  File "/home/hake/local/lib/python2.7/site-packages/ufl/split_functions.py", line 36, in split
    element = v.element()
AttributeError: 'ListTensor' object has no attribute 'element'

So we need to check that s is something splittable.