Just committing this because I managed to seg fault:
$ python simple.py
Solving linear system of size 801 x 801 (PETSc Krylov solver).
Solving on t = (0, 0.01)
Solving linear variational problem.
...
Solving on t = (0.09, 0.1)
Solving linear variational problem.
Solving linear variational problem.
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/libadjoint/libadjoint.py", line 541, in cfunc
    output = self(dependencies, values)
  File "/home/meg/local/fenics/lib/python2.7/site-packages/dolfin_adjoint/assign.py", line 38, in __call__
    return adjlinalg.Vector(values[0].data)
IndexError: list index out of range
Segmentation fault